name: CI-Fintexa

on:
  push:
    tags:
      - '*-dev'
      - '*-test'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Service A
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/services-a:${{ github.ref_name }} ./services-a
          docker push ${{ secrets.DOCKER_USERNAME }}/services-a:${{ github.ref_name }}

      - name: Build Service B
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/services-b:${{ github.ref_name }} ./services-b
          docker push ${{ secrets.DOCKER_USERNAME }}/services-b:${{ github.ref_name }}